apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: werf-guide-app
spec:
  rules:
  - host: {{ $.Values.global.host }}
    http:
      paths:
      - path: /ping
        pathType: Prefix
        backend:
          service:
            name: werf-guide-app
            port:
              number: 3000
