name: Production Deployment
on:
  push:
    branches: [master]
jobs:

  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - name: Login to Registry
#        uses: docker/login-action@v2
#        with:
#          registry: git.iconicompany.com
#          username: ${{ secrets.REGISTRY_USERNAME }}
#          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install werf
        uses: werf/actions/install@v1.2
        
      - name: Run script
        run: 
          werf cr login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} git.iconicompany.com;
          werf converge --repo git.iconicompany.com/iconicompany/werf-guide-app
        env:
          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
          WERF_ENV: production

#      - name: Converge
#        uses: werf/actions/converge@v1.2
#        with:
#          env: production
#          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
#        env:
#          WERF_SET_ENV_URL: "global.host=devel.iconicompany.com"
